version: '2'
volumes:
    mongodb: {}
services:
    webiny:
        user: '1000:1000'
        build: .
        volumes:
            - './:/app'
            - '~/.webiny/composer:/home/irvin/.cache/composer'
            - '~/.webiny/yarn-cache:/home/irvin/.cache/yarn'
        ports:
            - '8002:8002'
        environment:
            COMPOSER_HOME: /home/irvin/.cache/composer
            XDEBUG_CONFIG: remote_enable=0 remote_host=0.0.0.0
    nginx:
        image: 'nginx:alpine'
        ports:
            - '8000:80'
        volumes:
            - './:/app'
            - './docker-nginx.conf:/etc/nginx/conf.d/default.conf'
        networks:
            default:
                aliases:
                    - localhost.dev
    mongodb:
        image: mongo
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - 'mongodb:/data/db'
        ports:
            - '8001:27017'
        command: mongod --smallfiles --logpath=/dev/null
